version: '3.8'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
